import Onboarding from './components/onboarding/Onboarding';

export const gameData = [
  {
    name: '인물퀴즈',
    route: '/person',
    onboarding: {
      image: '/images/onboarding_person.png',
      recommendedPeople: '4-5명',
      difficulty: '☆☆',
      instructions: [
        { index: '1)', text: '순서를 정하세요.' },
        { index: '2)', text: '제시된 인물 사진을 보고\n인물의 이름을 맞춰 보세요.' },
      ],
    },
  },
  {
    name: '디스코',
    route: '/disco',
    onboarding: {
      image: '/images/onboarding_disco.png',
      recommendedPeople: '4-5명',
      difficulty: '☆☆☆☆☆',
      instructions: [
        { index: '1)', text: '제시된 단어를 보고, 그 단어가 들어간\n노래를 한 소절 불러주세요.' },
        { index: '2)', text: '앞에 나온 노래를 제외하고\n다른 노래를 한 소절씩 불러주세요.' },
        { index: '3)', text: '모든 팀원이 서로 다른 노래를 부르면\n성공입니다!' },
        { index: 'ex.', text: "ß사랑\n너무나 많이 ‘사랑'한 죄~\n: FT아일랜드 - 사랑앓이" },
      ],
    },
  },
  {
    name: '대표게임',
    route: '/captain',
    onboarding: {
      image: '/images/onboarding_captain.png',
      recommendedPeople: '5명',
      difficulty: '☆',
      instructions: [
        { index: '1)', text: '“우리 팀에서 가장 000한 사람”\n제시된 지문을 보고\n팀당 한 명씩 출전할 사람을 정해주세요!' },
        { index: '2)', text: '다음 페이지에 있는 미션을 클리어 하세요.' },
      ],
    },
  },
  {
    name: '네글자퀴즈',
    route: '/four',
    onboarding: {
      image: '/images/onboarding_four.png',
      recommendedPeople: '4-5명',
      difficulty: '☆☆',
      instructions: [
        { index: '1)', text: '순서를 정하세요.' },
        { index: '2)', text: '제시된 두 글자를 보고,\n뒤에 이어질 두 글자를 답해주세요.' },
        { index: 'ex.', text: '‘와이 _ _’\n 와이\'파이\'!' },
      ],
    },
  },
  {
    name: '단어텔레파시',
    route: '/tele',
    onboarding: {
      image: '/images/onboarding_wordTele.png',
      recommendedPeople: '4-5명',
      difficulty: '☆☆☆☆',
      instructions: [
        { index: '1)', text: '순서를 정하세요.' },
        { index: '2)', text: '제시된 글자로 시작하는 단어를\n생각하세요.' },
        { index: '3)', text: '자신의 단어를 순서대로 공개하세요.\n이 때 뒤로 갈수록 그 단어의 물리적인\n크기가 커져야 해요!' },
      ],
    },
  },
  {
    name: '텔레스트레이션',
    route: '/telestration',
    onboarding: {
      image: '/images/onboarding_teleStration.png',
      recommendedPeople: '4-5명',
      difficulty: '☆☆☆',
      instructions: [
        { index: '1)', text: '인원을 짝수로 맞춰 주세요.' },
        { index: '2)', text: '순서를 정한 후, 첫 순서를 제외한\n사람들은 뒤돌아 주세요.' },
        { index: '3)', text: '첫 사람은 제시어에 맞게 그림을 그린 후,\n종이를 다음 사람에게 전달해 주세요.' },
        { index: '4)', text: '받은 사람은 그림을 보고 답을 유추해 적은\n후, 다음 사람에게 종이를 전달해 주세요.' },
        { index: '5)', text: '그림 → 답 → 그림의 순서로 게임을\n진행하고, 마지막 사람은 그림을 보고\n답을 맞추세요.' },
      ],
    },
  },
  {
    name: '액션초성게임',
    route: '/choi',
    onboarding: {
      image: '/images/onboarding_choi.png',
      recommendedPeople: '4-5명',
      difficulty: '☆☆☆',
      instructions: [
        { index: '1)', text: '제공된 초성을 보고 떠오른 단어를\n몸으로 표현해 주세요.' },
        { index: '2)', text: '동작을 보고 정답을 맞춰 보세요.' },
      ],
    },
  },
  {
    name: '노래초성퀴즈',
    route: '/category',
    onboarding: {
      image: '/images/onboarding_music.png',
      recommendedPeople: '4-5명',
      difficulty: '☆☆☆☆☆',
      instructions: [
        { index: '1)', text: '제공된 초성을 보고, 주어진 카테고리에\n맞는 노래를 맞춰 보세요.' },
      ],
    },
  },
  {
    name: '명대사퀴즈',
    route: '/movie',
    onboarding: {
      image: '/images/onboarding_famous.png',
      recommendedPeople: '4-5명',
      difficulty: '☆☆☆☆',
      instructions: [
        { index: '1)', text: '영화나 드라마의 명장면 사진을 보고\n대사를 실감 나게 연기해 주세요.' },
      ],
    },
  },
];

// Church version removed

export const personData = [
  { name: '/person/류승범.WEBP', answer: '류승범' },
  { name: '/person/강동원.WEBP', answer: '강동원' },
  { name: '/person/남도일.jpeg', answer: '남도일' },
  { name: '/person/강백호.jpeg', answer: '강백호' },
  { name: '/person/공유.WEBP', answer: '공유' },
  { name: '/person/미나.WEBP', answer: '미나' },
  { name: '/person/김태희.jpeg', answer: '김태희' },
  { name: '/person/송혜교.WEBP', answer: '송혜교' },
  { name: '/person/박재범.WEBP', answer: '박재범' },
  { name: '/person/수지.JPG', answer: '수지' },
  { name: '/person/김동현.WEBP', answer: '김동현' },
  { name: '/person/링컨.WEBP', answer: '링컨' },
  { name: '/person/유관순.WEBP', answer: '유관순' },
  { name: '/person/데드풀.jpeg', answer: '데드풀' },
  { name: '/person/로버트 다우니 주니어.jpeg', answer: '로버트 다우니 주니어' },
  { name: '/person/민경훈.jpeg', answer: '민경훈' },
  { name: '/person/보노보노.WEBP', answer: '보노보노' },
  { name: '/person/스칼렛요한슨.JPG', answer: '스칼렛요한슨' },
  { name: '/person/올라프.JPG', answer: '올라프' },
  { name: '/person/이승우.jpeg', answer: '이승우' },
  { name: '/person/안재홍.WEBP', answer: '안재홍' },
  { name: '/person/손흥민.JPG', answer: '손흥민' },
  { name: '/person/강하늘.WEBP', answer: '강하늘' },
  { name: '/person/거미.WEBP', answer: '거미' },
  { name: '/person/고윤정.WEBP', answer: '고윤정' },
  { name: '/person/미달이.WEBP', answer: '미달이' },
  { name: '/person/뿡뿡이.WEBP', answer: '뿡뿡이' },
  { name: '/person/어피치.png', answer: '어피치' },
  { name: '/person/해린.JPG', answer: '해린' },
  { name: '/person/저스틴 비버.png', answer: '저스틴 비버' },
  { name: '/person/조정석.WEBP', answer: '조정석' },
  { name: '/person/조유리.png', answer: '조유리' },
  { name: '/person/정동원.jpeg', answer: '정동원' },
  { name: '/person/무민.JPG', answer: '무민' },
  { name: '/person/샘스미스.WEBP', answer: '샘스미스' },
  { name: '/person/현주엽.WEBP', answer: '현주엽' },
  { name: '/person/전여빈.WEBP', answer: '전여빈' },
  { name: '/person/김연경.jpeg', answer: '김연경' },
  { name: '/person/타노스.WEBP', answer: '타노스' },
  { name: '/person/김소연.WEBP', answer: '김소연' },
  { name: '/person/조승우.JPG', answer: '조승우' },
  { name: '/person/안나.JPG', answer: '안나' },
  { name: '/person/포돌이.WEBP', answer: '포돌이' },
  { name: '/person/이문세.WEBP', answer: '이문세' },
  { name: '/person/문상훈.WEBP', answer: '문상훈' },
  { name: '/person/지성.WEBP', answer: '지성' },
  { name: '/person/이경영.WEBP', answer: '이경영' },
  { name: '/person/피오나.WEBP', answer: '피오나' },
  { name: '/person/윈터.jpeg', answer: '윈터' },
  { name: '/person/고아성.WEBP', answer: '고아성' },
  { name: '/person/김연자.jpeg', answer: '김연자' },
  { name: '/person/마동석.jpeg', answer: '마동석' },
  { name: '/person/임영웅.jpeg', answer: '임영웅' },
  { name: '/person/장윤주.jpeg', answer: '장윤주' },
  { name: '/person/차두리.jpeg', answer: '차두리' },
  { name: '/person/나영석.WEBP', answer: '나영석' },
  { name: '/person/노진구.JPG', answer: '노진구' },
  { name: '/person/유해진.WEBP', answer: '유해진' },
  { name: '/person/최우식.JPG', answer: '최우식' },
  { name: '/person/크러쉬.JPG', answer: '크러쉬' },
  { name: '/person/박명수.WEBP', answer: '박명수' },
  { name: '/person/봉준호.WEBP', answer: '봉준호' },
  { name: '/person/일론 머스크.WEBP', answer: '일론 머스크' },
  { name: '/person/안유진.JPG', answer: '안유진' },
  { name: '/person/아이유.jpeg', answer: '아이유' },
  { name: '/person/장원영.jpg', answer: '장원영' },
  { name: '/person/유재석.webp', answer: '유재석' },
  { name: '/person/조세호.jpg', answer: '조세호' },
  { name: '/person/카리나.png', answer: '카리나' },
  { name: '/person/뽀로로.jpg', answer: '뽀로로' },
  { name: '/person/도라에몽.jpg', answer: '도라에몽' },
  { name: '/person/미키마우스.webp', answer: '미키마우스' },
  { name: '/person/하니.jpg', answer: '하니' },
  { name: '/person/제니.webp', answer: '제니' },
  { name: '/person/뷔.png', answer: '뷔' },
  { name: '/person/박보검.png', answer: '박보검' },
  { name: '/person/오은영.webp', answer: '오은영' },
  { name: '/person/김태리.webp', answer: '김태리' },
  { name: '/person/손석구.jpg', answer: '손석구' },
  { name: '/person/나문희.webp', answer: '나문희' },
  { name: '/person/박서준.jpg', answer: '박서준' },
  { name: '/person/박진영.jpg', answer: '박진영' },
  { name: '/person/스티브잡스.webp', answer: '스티브잡스' },
  { name: '/person/이제훈.jpeg', answer: '이제훈' },
  { name: '/person/티모시 샬라메.jpg', answer: '티모시 샬라메' },
  { name: '/person/한소희.jpg', answer: '한소희' },
];

export const discoData = [
  { name: '사랑' },
  { name: '너' },
  { name: '나' },
  { name: '우리' },
  { name: '봄' },
  { name: '여름' },
  { name: '가을' },
  { name: '겨울' },
  { name: '당신' },
  { name: '미안' },
  { name: '손' },
  { name: '바다' },
  { name: '하늘' },
  { name: '엄마' },
  { name: '이별' },
  { name: '눈물' },
  { name: '꽃' },
  { name: '서로' },
  { name: '인연' },
  { name: '널' },
  { name: '안녕' },
  { name: '진심' },
  { name: '마음' },
  { name: 'Love' },
  { name: 'You' },
  { name: 'Baby' },
  { name: '인사' },
  { name: '눈' },
  { name: '비' },
  { name: '바람' },
  { name: '생각' },
  { name: '가슴' },
  { name: '고백' },
  { name: '우주' },
  { name: '별' },
  { name: 'star' },
  { name: '나무' },
  { name: '자유' },
  { name: '미련' },
  { name: '정말' },
  { name: '행복' },
  { name: '하루' },
  { name: '거짓말' },
  { name: '풍선' },
  { name: 'bye' },
  { name: 'my' },
  { name: '오늘' },
  { name: '어제' },
  { name: '내일' },
  { name: '친구' },
  { name: '꿀 honey' },
  { name: '꿈' },
  { name: '밤' },
  { name: '낮' },
];

export const captainData = [
  { name: '가장 유연할\n것 같은 사람', answer: '옆사람과 다리찢기\n가위바위보 해서 이기기' },
  { name: '가장 노래를 잘\n부를 것 같은 사람', answer: '절대음감' },
  { name: '대머리가 제일 잘\n어울릴 것 같은 사람', answer: '이마 길이 재기' },
  { name: '공부 제일 잘할\n것 같은 사람', answer: '구구단 10문제 맞추기' },
  { name: '가장 춤 잘출\n것 같은 사람', answer: '포스트잇 빨리 떼기' },
  { name: '가장 운동 잘할\n것 같은 사람', answer: '한 발 들고\n오래 버티기' },
  { name: '수업 시간에 졸\n것 같은 사람', answer: '옆사람과 눈싸움해서 이기기' },
  { name: '고등학생 때 담 넘어봤을 것 같은 사람', answer: '멀리뛰기 \n가장 멀리뛰기' },
  { name: '정색 가장 잘할\n것 같은 사람', answer: '1분 동안 웃음 참기' },
  { name: '가장 당당해 보이는 사람', answer: '옆사람과 당연하지 게임 해서 이기기' },
  { name: '사회생활 잘할 \n것 같은 사람', answer: '눈치게임' },
  { name: '눈물 많을\n것 같은 사람', answer: '눈물 빨리 흘리기' },
  { name: '무인도에서 살아남을 수\n있을 것 같은 사람', answer: '무인도에 가져갈 물건 사람들 앞에서 PT하고 납득시키기' },
  { name: '과자를 가장 많이 먹을\n것 같은 사람', answer: '과자 부스러기 보고\n과자 맞추기' },
  { name: '요리 잘 할\n것 같은 사람', answer: '후라이펜 놀이' },
  { name: '끈기 있는 사람', answer: '페트병 빨리 세우기' },
  { name: '문자보다 전화를 더 좋아할 것 같은 사람', answer: '가장 최근 연락한 사람에게 전화해서 칭찬 듣기' },
  { name: 'SNS 가장 많이 할\n것 같은 사람', answer: '눈 감고 오늘 자신의 TMI를 타자로 치기' },
  { name: '감수성이 가장 풍부할\n것 같은 사람', answer: '자신의 이름으로 삼행시 짓기' },
  { name: '연애 제일 많이 해봤을거 같은 사람', answer: '가족에게 전화해서 사랑한다고 말하기' },
];

export const fourData = [
  { name: '이구 _ _' },
  { name: '동문 _ _' },
  { name: '드라 _ _' },
  { name: '게르 _ _' },
  { name: '안전 _ _' },
  { name: '고슴 _ _' },
  { name: '오토 _ _' },
  { name: '파인 _ _' },
  { name: '레이 _ _' },
  { name: '예방 _ _' },
  { name: '고객 _ _' },
  { name: '샌드 _ _' },
  { name: '유통 _ _' },
  { name: '호랑 _ _' },
  { name: '술래 _ _' },
  { name: '프리 _ _' },
  { name: '분리 _ _' },
  { name: '초코 _ _' },
  { name: '해바 _ _' },
  { name: '코스 _ _' },
  { name: '카놀 _ _' },
  { name: '어린 _ _' },
  { name: '일기 _ _' },
  { name: '백설 _ _' },
  { name: '헤드 _ _' },
  { name: '보사 _ _' },
  { name: '폼클 _ _' },
  { name: '오랑 _ _' },
  { name: '나무 _ _' },
  { name: '차돌 _ _' },
  { name: '치즈 _ _' },
  { name: '다이 _ _' },
  { name: '김치 _ _' },
  { name: '자급 _ _' },
  { name: '다이 _ _' },
  { name: '다사 _ _' },
  { name: '이모 _ _' },
  { name: '장기 _ _' },
  { name: '인테 _ _' },
  { name: '감자 _ _' },
  { name: '직사 _ _' },
  { name: '계란 _ _' },
  { name: '피라 _ _' },
  { name: '와이 _ _' },
  { name: '무당 _ _' },
  { name: '페이 _ _' },
  { name: '아나 _ _' },
  { name: '개미 _ _' },
  { name: '코카 _ _' },
  { name: '오피 _ _' },
  { name: '육삼 _ _' },
  { name: '아이 _ _' },
  { name: '부루 _ _' },
  { name: '메타 _ _' },
  { name: '포토 _ _' },
  { name: '블루 _ _' },
  { name: '마스 _ _' },
  { name: '장기 _ _' },
  { name: '장래 _ _' },
  { name: '개과 _ _' },
  { name: '내로 _ _' },
  { name: '슈퍼 _ _' },
  { name: '르세 _ _' },
  { name: '아이 _ _' },
  { name: '손목 _ _' },
  { name: '스핑 _ _' },
  { name: '봅슬 _ _' },
  { name: '보디 _ _' },
  { name: '비상 _ _' },
  { name: '게이 _ _' },
  { name: '오토 _ _' },
  { name: '강강 _ _' },
  { name: '타임 _ _' },
  { name: '콩쥐 _ _' },
  { name: '유체 _ _' },
  { name: '납작 _ _' },
  { name: '회전 _ _' },
  { name: '먹이 _ _' },
  { name: '아프 _ _' },
];

// Church datasets removed

export const teleData = [
  { name: '가' },
  { name: '다' },
  { name: '나' },
  { name: '물' },
  { name: '자' },
  { name: '우' },
  { name: '하' },
  { name: '기' },
  { name: '이' },
  { name: '산' },
  { name: '시' },
  { name: '아' },
  { name: '화' },
  { name: '마' },
  { name: '조' },
  { name: '모' },
  { name: '도' },
  { name: '라' },
  { name: '호' },
  { name: '이' },
  { name: '레' },
  { name: '내' },
  { name: '네' },
  { name: '사' },
  { name: '감' },
  { name: '기' },
  { name: '가' },
  { name: '아' },
  { name: '마' },
  { name: '이' },
  { name: '중' },
  { name: '미' },
  { name: '일' },
  { name: '우' },
  { name: '자' },
  { name: '라' },
  { name: '나' },
  { name: '모' },
  { name: '인' },
  { name: '민' },
  { name: '지' },
  { name: '물' },
  { name: '불' },
  { name: '산' },
  { name: '거' },
  { name: '토' },
  { name: '월' },
  { name: '나' },
  { name: '구' },
  { name: '원' },
];

export const telestrationData = [
  { name: '스컹크' },
  { name: '쿼카' },
  { name: '엑스레이' },
  { name: '번지점프' },
  { name: '통나무집' },
  { name: '공중전화' },
  { name: '해외직구' },
  { name: '미키마우스' },
  { name: '찰리채플린' },
  { name: '수족관' },
  { name: '에펠탑' },
  { name: '개미핥기' },
  { name: '에어로빅' },
  { name: '필라테스' },
  { name: '합창단' },
  { name: '어부' },
  { name: '허수아비' },
  { name: '치과의사' },
  { name: '암벽등반' },
  { name: '개그맨' },
  { name: '경찰서' },
  { name: '판사' },
  { name: '연필깎이' },
  { name: '타코야끼' },
  { name: '금붕어' },
  { name: '구미호' },
  { name: '제빵사' },
  { name: '평양냉면' },
  { name: '크루아상' },
  { name: '물개' },
  { name: '티라노사우루스' },
  { name: '우주정거장' },
  { name: '서예' },
  { name: '주먹도끼' },
  { name: '빗살무늬토기' },
  { name: '면접' },
  { name: '야근' },
  { name: '삼계탕' },
  { name: '이순신장군' },
  { name: '감자탕' },
  { name: '낙동강' },
  { name: '연어' },
  { name: '다이빙' },
  { name: '고구려' },
  { name: '선생님' },
  { name: '경전철' },
  { name: '물회' },
  { name: '디자이너' },
  { name: '미역' },
  { name: '북극곰' },
  { name: '정전기' },
  { name: '솜사탕' },
  { name: '면도크림' },
  { name: '독수리' },
  { name: '콧노래' },
  { name: '좀비' },
  { name: '비누' },
  { name: '셜록홈즈' },
  { name: '엽서' },
  { name: '조각 케이크' },
  { name: '축제' },
  { name: '구호' },
  { name: '하프' },
  { name: '__<-진행자 맘대로' },
  { name: '연필깍이' },
  { name: '페디큐어' },
  { name: '번지점프' },
  { name: '당구장' },
  { name: '카지노' },
  { name: '미역국' },
  { name: '외발자전거' },
  { name: '탁구' },
  { name: '도서관' },
  { name: '도서관' },
  { name: '밥도둑' },
  { name: '중고차' },
  { name: '추석' },
  { name: '다람쥐' },
  { name: '애벌레' },
  { name: '두꺼비' },
  { name: '고구마' },
  { name: '스파게티' },
  { name: '판다' },
  { name: '놀이터' },
  { name: '팝콘' },
  { name: '겁쟁이' },
  { name: '초밥' },
  { name: '해적' },
  { name: '스누피' },
  { name: '닭다리' },
  { name: '치킨' },
  { name: '편의점' },
  { name: '고무줄' },
  { name: '스노우보드' },
  { name: '돈까스' },
  { name: '각시탈' },
  { name: '남산타워' },
  { name: '백화점' },
  { name: '화산' },
];

export const choiData = [
  { name: 'ㄷ ㅁ' },
  { name: 'ㅁ ㄹ' },
  { name: 'ㄱ ㄷ' },
  { name: 'ㅈ ㄱ' },
  { name: 'ㄴ ㅇ' },
  { name: 'ㄱ ㄹ' },
  { name: 'ㅁ ㄱ' },
  { name: 'ㄱ ㅅ' },
  { name: 'ㄷ ㄹ' },
  { name: 'ㅎ ㅎ' },
  { name: 'ㄱ ㅇ' },
  { name: 'ㅅ ㄷ' },
  { name: 'ㅇ ㅈ' },
  { name: 'ㅂ ㅇ' },
  { name: 'ㄴ ㄱ' },
  { name: 'ㄱ ㅂ' },
  { name: 'ㅂ ㅈ' },
  { name: 'ㅇ ㄱ' },
  { name: 'ㅅ ㄱ' },
  { name: 'ㄴ ㄹ' },
  { name: 'ㄱ ㅊ' },
  { name: 'ㅂ ㅁ' },
  { name: 'ㄴ ㅂ' },
  { name: 'ㅇ ㅁ' },
  { name: 'ㄷ ㄱ' },
  { name: 'ㄱ ㄱ' },
  { name: 'ㅅ ㅁ' },
  { name: 'ㅁ ㅁ' },
  { name: 'ㄷ ㅂ' },
  { name: 'ㅂ ㅈ' },
  { name: 'ㄱ ㅈ' },
  { name: 'ㅁ ㅇ' },
  { name: 'ㅅ ㅈ' },
  { name: 'ㅍ ㄹ' },
  { name: 'ㅁ ㅂ' },
  { name: 'ㄴ ㅁ' },
  { name: 'ㅎ ㅇ' },
  { name: 'ㄷ ㅇ' },
  { name: 'ㅂ ㅅ' },
  { name: 'ㅅ ㄹ' },
  { name: 'ㅇ ㅅ' },
  { name: 'ㅂ ㄱ' },
  { name: 'ㄷ ㅈ' },
  { name: 'ㅈ ㅅ' },
  { name: 'ㅅ ㅇ' },
  { name: 'ㅇ ㄹ' },
  { name: 'ㅂ ㅎ' },
  { name: 'ㅎ ㅅ' },
  { name: 'ㅇ ㅂ' },
  { name: 'ㅂ ㅂ' },
];

export const music1990Data = [
  { name: 'ㄴㅂ - ㅈㅇㅍ', answer: '나비 - 조용필' },
  { name: 'ㅅㄹㅎㅇ - ㄱㅇㅅ', answer: '사랑해요 - 김완선' },
  { name: 'ㅅㄹㅇ ㅇㅅㅇ \nㅇㅇㄷㅁ - ㅇㅈㅂ', answer: '사랑에\n연습이 있었다면 - 임재범' },
  { name: 'ㄴ ㅇㅇㅇ \n- ㅅㅌㅈ', answer: '난 알아요 - 서태지' },
  { name: 'ㄱ ㅈㅇ ㄱㄷㄹ\n ㅁㄴ - ㅇㅅㅎ', answer: '그 중에 그대를 \n만나 - 이선희' },
  { name: 'ㅎㅂㄹㄱ - ㅎㄷㅈ', answer: '해바라기 - 한동준' },
  { name: 'ㅈㅁㄷ ㅁㄴ\n- ㄱㄱㅁ', answer: '잘못된 만남\n- 김건모' },
  { name: 'ㄱㄹ ㅅㄹ ㄸ\nㅇㅅㄴㅅ - ㄷㄷ', answer: '그런 사람 또\n없습니다 - 더더' },
  { name: 'ㅁㄹㅅㄱ\n- ㄷ ㅋㄹㅅ', answer: '모래시계\n- 더 클래식' },
  { name: 'ㅇㅇㄴ - ㅈㅎㅈ ', answer: '잊었니 - 장혜진' },
  { name: 'ㄴㅈ ㅁㅎㅊㄹ\n- ㄹㄹ', answer: '남자 만화처럼\n- 룰라' },
  { name: 'ㄴㄹ ㅍㅇ ㅇㅇㅁ\n- ㄱㅎㅅ', answer: '너를 품에 안으면\n- 김현식' },
  { name: 'ㄴㅇㄱㄹ ㄸ\nㄱㄱ ㅅㅇ\n- ㅇㅈㅅ', answer: '너에게로 또\n가고 싶어\n- 이정석' },
  { name: 'ㅂㄲ ㅇㄷ\n- ㅅㅂㅊ', answer: '벚꽃 엔딩\n- 소방차' },
  { name: 'ㄴ ㅇㅇㅇ ㄱㅂㅇ\n- ㄱㅅㅎ', answer: '내 이름은 권보아\n- 김수희' },
  { name: 'ㄷ ㅅ ㅁㅇ\n- ㅇㅂㅈㅋㅍ', answer: '두 손 모아\n- 어반자카파' },
  { name: 'ㅇㄹ ㅇㅂㅎㄷ\nㅈㄱㅈ - ㅇㅌㅇ', answer: '우리 이별했던\n정거장- 원타임' },
  { name: 'ㅅㄹㅇㅃㅇ\n- ㅇㅈㅎ', answer: '사랑일뿐야\n- 엄정화' },
  { name: 'ㄴㅇㄱㄹ ㄸ\nㄱㄱ ㅅㅇ', answer: '너에게로 또\n가고 싶어' },
  { name: 'ㄴㅁㅇ - ㅎㄷㅈ', answer: '너만이 - 한동준' },
  { name: 'ㅊㅎ\n- ㅂㅇㄹㄱㅇㄱㅇ', answer: '청혼\n- 봄여름가을겨울' },
  { name: 'ㅇㅈㅊㄹ - ㄱㄱㅎ', answer: '어제처럼 - 김경호' },
  { name: 'ㅎㅎㅎㅆ - ㅈㅇㄹ', answer: '하하하쏭 - 자우림' },
  { name: 'ㅂㅅ - ㅈㅅ', answer: '비상 - 조선' },
  { name: 'ㄱㅇ ㅅㅇ ㅁㅅ\n- ㄱㅇㅅ', answer: '기억 속의 미소\n- 김완선' },
  { name: 'ㅇㅂㅈ - ㅇㅅㄱ', answer: '아버지 - 이승기' },
  { name: 'ㅊㅇ ㄱ ㄴㄲㅊㄹ\n- ㄹ', answer: '처음 그 느낌처럼\n- 린' },
  { name: 'ㅇㅇㅇ ㅎㄷㄴ\nㅁㅇㅇㄹ\n-  ㄱㄱㅁ', answer: '잊어야 한다는\n마음으로\n- 김건모' },
  { name: 'ㅇㅅㅎ ㅇㅎ - ㅋ', answer: '이상한 여행 - 쿨' },
  { name: 'ㅎㅇ\n- ㅇㄷㅎㅂㄷ', answer: '희야\n- 윤도현밴드' },
  { name: 'ㅇㅂㅇ ㅈㄴㅁ\n- ㅅㅌㅈㅇ ㅇㅇㄷ', answer: '이밤이 지나면\n- 서태지와 아이들' },
  { name: 'ㅂㄱㅂㄱ - ㅈㅅㅁ', answer: '빙글빙글 - 조성모' },
  { name: 'ㅂㄹㅇ ㅂㅇㅇㅁ\nㅈㄱㅇ\n- ㅇㄷㅎㅂㄷ', answer: '바람이 불었으면\n좋겠어\n- 윤도현밴드' },
  { name: 'ㅁㄴ ㅋㅍ\n- ㄱㅁㅈ', answer: '모닝 커피\n- 김민종' },
  { name: 'ㄱㅅ ㅇㄷㅇ\n- ㅅㅌㅈㅇ ㅇㅇㄷ', answer: '교실 이데아\n- 서태지와 아이들' },
  { name: 'ㅇㄸㄱㅇ\n- ㅈㅎㅈ', answer: '어떤가요\n- 장혜진' },
  { name: 'ㅂㄹㅇ ㄴㄹ\n- ㄱㅎㄹ', answer: '바람의 노래\n- 김학래' },
  { name: 'ㄴ ㅇㄹㅈ ㄲ\n- ㅌㅂ', answer: '나 어릴적 꿈\n- 터보' },
  { name: 'ㅇㄷㅇ\n- ㅈㅁㅇㄱ', answer: '안돼요\n- 장미여관' },
  { name: 'ㅈㄴ - ㅇㅈㅅ', answer: '자니 - 이정석' },
  { name: 'ㅇㄸㄱ ㅅㄹㅇ\nㄱㄹㅇ - ㅎㅌㅈ', answer: '어떻게 사랑이\n그래요 - 황태지' },
  { name: 'ㅇㅂ ㄱㄹㄱ ㅁㄹ\n- ㅂㅁㄱ', answer: '이별 그리고 미련\n- 박미경' },
  { name: 'ㅁㅂㅇ ㅊㅊ\n- ㅅㅌㅈㅇ ㅇㅇㄷ', answer: '맨발의 청춘\n- 서태지와 아이들' },
  { name: 'ㄱ ㄴㅈ ㄱ ㅇㅈ\n- ㅇㅁㅅ', answer: '그 남자 그 여자\n- 이문세' },
  { name: 'ㅂㄹㄱㅇ ㅅㅇ\n- ㅈㅇㅍ', answer: '바람결에 실어\n- 조용필' },
  { name: 'ㅅㄹㅎㅈㅁ\n- ㅇㅅㅎ', answer: '사랑했지만\n- 이승환' },
  { name: 'ㄴㄴ ㅇㄹㅇ\n- ㅋ', answer: '나는 외로워\n- 쿨' },
  { name: 'ㄷㅈ\n- ㄷ ㅋㄹㅅ', answer: '답장\n- 더 클래식' },
  { name: 'ㅁㅎㅈ ㅁ\n- ㅈㅅ', answer: '말하지 마\n- 조선' },
  { name: 'ㅅㄹㅎ ㅎㅇ\n- ㄱㅁㅇ', answer: '사랑한 후에\n- 김민우' },
  { name: 'ㄴㅅㄹ ㄴㄱㅇ - ㄱㅎㅅ', answer: '내사랑 내곁에 - 김현식' },
  { name: 'ㄴㄹ ㅅㄹㅎ - ㅎㄷㅈ', answer: '너를 사랑해 - 한동준' },
  { name: 'ㄷㅅㅇ ㅁㄴ ㄴㅇㄱ - ㅍㄴㅋㅇ', answer: '다시 만난 너에게 - 피노키오' },
  { name: 'ㄴㅇ ㄴㄹ - ㄱㄱㅅ', answer: '나의 노래 - 김광석' },
  { name: 'ㅇㄹㅈ ㅇㅇㄷ ㅇㅇㄷ - ㄱㅇㅇㅂ', answer: '아주 오래된 연인들 - ㄱㅇㅇㅂ' },
  { name: 'ㅇㅂㅇ ㄱㄴ - ㅇㅅ', answer: '이별의 그늘 - 윤상' },
  { name: 'ㄴㄱ - ㅇㅅㅎ', answer: '내게 - 이승환' },
  { name: 'ㅍㅇㅈ - ㅇㅈㅎ', answer: '포이즌 - 엄정화' },
  { name: 'ㄴㄱ ㅁㅇ - ㅇㅊㅎ', answer: '내가 만일 - 안치환' },
  { name: 'ㄷㅅㅇ - ㄴㄱㅌ', answer: '도시인 - 넥스트' },
  { name: 'ㅇㅁ - ㄱㅅㅎ', answer: '애모 - 김수희' },
  { name: 'ㄴㄹ ㅎㅎ ㅁㅇ - ㅇㅅㅎ', answer: '너를 향한 마음 - 이승환' },
  { name: 'ㅇ ㅂㅇ ㅈㄴㄷㄹ - ㅍㄹ ㅎㄴ', answer: '이 밤이 지나도록 - 푸른 하늘' },
  { name: 'ㅎㅁㅅㅎ - ㅂㅈㅅ', answer: '희망사항 - 변진섭' },
  { name: 'ㄴㄷㄹ - ㄱㅎㅅ', answer: '넋두리 - 김현식' },
  { name: 'ㅍㄱ - ㄱㄱㅁ', answer: '핑계 - 김건모' },
  { name: 'ㅅ ㅇㄹㅇ ㅅㄹ - ㄱㅇㅇㅂ', answer: '신 인류의 사랑 - ㄱㅇㅇㅂ' },
  { name: 'ㅅㄹㅇ ㅇㅎㅇ - ㄱㅈㅎ', answer: '사랑을 위하여 - 김종환' },
  { name: 'ㄴㅇㄱ ㄷㄹㅈㄱ ㅅㅇ ㅇㅇㄱ - ㄱㅇㅇㅂ', answer: '너에게 들려주고 싶은 이야기 - ㄱㅇㅇㅂ' },
  { name: 'ㅇㄹㅊㅇ ㅂ - ㅎㅂㅊ', answer: '유리창엔 비 - 햇빛촌' },
  { name: 'ㄷㅍㅇ - ㅍㄴ', answer: '달팽이 - 패닉' },
  { name: 'ㅅㅊ ㅇ ㅈㅎㅊ ㅇㅇㅅ - ㄷㅁㅇ', answer: '시청 앞 지하철 역에서 - 동물원' },
  { name: 'ㄲㅇㅅ ㅂ ㄱㄹ - ㅍㄹ ㅎㄴ', answer: '꿈에서 본 거리 - 푸른 하늘' },
  { name: 'ㅅㄹㅎㅅㄹ - ㅂㅎ', answer: '사랑할수록 - 부활' },
  { name: 'ㄷㅇ ㅁㄹ - ㄱㅎㅊ', answer: '달의 몰락 - 김현철' },
  { name: 'ㄱㅇㅇ ㅅㅈ - ㅈㄹㅎ', answer: '기억의 습작 - 전람회' },
  { name: 'ㅁㅅ ㅅㅇ ㅂㅊ ㄱㄷ - ㅅㅅㅎ', answer: '미소 속에 비친 그대 - 신승훈' },
  { name: 'ㄴㄹ ㅅㅍㄱ ㅎㄴ ㅅㄹㄷ - ㄱㄱㅎ', answer: '나를 슬프게 하는 사람들 - 김경호' },
  { name: 'ㄸ ㄷㄹ ㅁㄴㅇ ㅇㅎ - ㄱㅁㅈ', answer: '또 다른 만남을 위해 - 김민종' },
  { name: 'ㄱ ㅎㄹ ㅇㄹㄷㅇ - ㅅㅅㅎ', answer: '그 후로 오랫동안 - 신승훈' },
  { name: 'ㄷㅅㄴ ㅇㄷ ㅇㄴㅇ - ㅇㅅㄱ', answer: '당신은 어디 있나요 - 양수경' },
  { name: 'ㅂㅇㄴ ㄴ ㅅㅊㅎ - ㄱㅎㅅ', answer: '비오는 날 수채화 - 김현식' },
  { name: 'ㅇㅈㄴ ㄱ ㅈㄹㅇ - ㅅㅎㅂ', answer: '언제나 그 자리에 - 신효범' },
  { name: 'ㅅㄹㅇ ㅎㄲㅇ - ㄴㅅㅈㄷ', answer: '사랑을 할꺼야 - 녹색지대' },
  { name: 'ㅇㄹㅈ ㄱㄴ - ㅇㅈㅅ', answer: '오래전 그날 - 윤종신' },
  { name: 'ㅁㅈㅇ ㅋㅅㅌ - ㅇㅅㅊ', answer: '마지막 콘서트 - 이승철' },
  { name: 'ㅂㄱㅅㅇ ㅇㄱ - ㅁㅎㄱ', answer: '보고싶은 얼굴 - 민해경' },
  { name: 'ㄴ ㅎ ㅅ ㅇㅇ - ㄱㅅㅇ', answer: '넌 할 수 있어 - 강산에' },
  { name: 'ㄱㄷㅍㅇ ㅈㄷㅇㅇㅁ - ㅂㅈㅅ', answer: '그대품에 잠들었으면 - 박정수' },
  { name: 'ㅂㅎ - ㅇㅅㅊ', answer: '방황 - 이승철' },
  { name: 'ㄴㄹ ㅅㄹㅎㄱㄷ - ㅈㅇㄴ', answer: '너를 사랑하고도 - 전유나' },
  { name: 'ㄴㅇ ㄱㅎㅅ - ㅇㅈㅅ', answer: '너의 결혼식 - 윤종신' },
  { name: 'ㅇ ㅂㅇ ㄲㅇ ㅈㄱ - ㅅㄹㄷ', answer: '이 밤의 끝을 잡고 - 솔리드' },
  { name: 'ㅁㅂㅇ ㅅ - ㄷ ㅋㄹㅅ', answer: '마법의 성 - 더 클래식' },
  { name: 'ㅁㅈㄱ ㄷㅇ - ㅇㅇㅅ', answer: '먼지가 되어 - 이윤수' },
  { name: 'ㄴ ㅎㅍㅎ - ㅇㅅㄹ', answer: '난 행복해 - 이소라' },
  { name: 'ㅇㄴ ㄱㅇ ㅂㅇㅁ - ㅂㅈㅇ', answer: '오늘 같은 밤이면 - 박정운' },
  { name: 'ㅂㅇㅈ ㅇㄴ ㅅㄹ - ㅅㅅㅎ', answer: '보이지 않는 사랑 - 신승훈' },
  { name: 'ㄱㄷㅇㅇ ㅂㄹ - ㄱㅎㅊ, ㅇㅅㄹ', answer: '그대안의 블루 - 김현철, 이소라' },
];

export const music2000Data = [
  { name: 'ㅈㅈ\n- ㅂㄹㅇ ㅇㅇㅈ', answer: '점점\n- 브라운 아이즈' },
  { name: 'ㄴㅇ ㄲ - ㅂㅎㅅ', answer: '눈의 꽃 - 박효신' },
  { name: 'ㅅㄹㅎㄴㅂ\n- ㅇㄷㅎ', answer: '사랑했나봐\n- 윤도현' },
  { name: 'ㅁㅈㅁ ㅇㅅ - ㅂㅂ', answer: '마지막 인사 - 빅뱅' },
  { name: 'ㅎㄹ ㅎㄹ - ㅂㅂ', answer: '하루 하루 - 빅뱅' },
  { name: 'ㅅㄹ ㅇㅇ\n- ㅇㅍㅌ ㅇㅇㄹㄷ', answer: '사랑 앓이\n- FT아일랜드' },
  { name: 'ㅊㄱㅇ - ㅇㅅㅇ', answer: '친구여 - 인순이' },
  { name: 'ㄱㅅ - ㄱㄷㄹ', answer: '감사 - 김동률' },
  { name: 'ㅎㅈ ㅅ ㅇㄴ ㅇ\n- ㅂㅎㅅ', answer: '해줄 수 없는 일 \n- 박효신' },
  { name: 'ㄱㅈㅁ - ㅂㅂ', answer: '거짓말 - 빅뱅' },
  { name: 'ㅊㅁㅇㄱㅊㄹ\n- ㅂㅈㅇ', answer: '총맞은것처럼\n- 백지영' },
  { name: 'ㄴ ㄴᄅ ᄉᄅᄒ\n- ᄉᄒᄇ', answer: '난 너를 사랑해\n- 신효범' },
  { name: 'ᄀᄃᄀ ᄇᄃ\n- ㅇㅅᄎ', answer: '그대가 분다\n- ㅇㅅᄎ' },
  { name: 'ㄴㅅㄹ- ㅇㅅㅈㅇㄴㅂ', answer: '내사람- 에스지워너비' },
  { name: 'ㅅㅋㅅ\n- ㅇㅆㅁ', answer: '서커스\n- 엠씨몽' },
  { name: 'ㄴㄱ ㅇㄴㄱ\nㅇㄴㅇ - ㄹㅆ', answer: '내가 웃는게\n아니야 - 리쌍' },
  { name: 'ㅌㅁ - ㅇㄷㄱㅅ', answer: '텔미 - 원더걸스' },
  { name: 'ㅅㅇㅇ ㅁㅎㅂ\n- ㅅㄴㅅㄷ', answer: '소원을 말해봐\n- 소녀시대' },
  { name: 'ㅂㅆ ㅇㄴ\n- ㅂㄹㅇㅇㅇㅈ', answer: '벌써 일년\n- 브라운아이즈' },
  { name: 'ㄷㅅ ㅅㄹㅎㄷ\nㅁㅎㄲ - ㄱㄷㄹ', answer: '다시 사랑한다\n말할까 - 김동률' },
  { name: 'ㄴㄱ ㅇㄴ ㄱ\n- ㅅㅅㄱ', answer: '내게 오는 길\n- 성시경' },
  { name: 'ㅇㄹㅎ - ㅋ', answer: '아로하 - 쿨' },
  { name: 'ㄴㅁㄱㅇㅇ\n- ㅊㄹㅍㅌ', answer: '낭만고양이\n- 체리필터' },
  { name: 'ㅂㅁ\n- ㅋㅇㅌ', answer: '비몽\n- 코요태' },
  { name: 'ㅇㅌㄹㅌㅅ ㅅㄴ\n- ㅂㅇ', answer: '아틀란티스 소녀\n- 보아' },
  { name: 'ㅊㄴ - ㅂㅁㅁ', answer: '체념 - 빅마마' },
  { name: 'ㄱㅎㅁ ㅇㄱ\n- ㅇㅅㅇ', answer: '광화문 연가\n- 이수영' },
  { name: 'ㅂㅊㅂ - ㅎㅅ', answer: '불치병 - 휘성' },
  { name: 'ㅈㅇ ㅅㄹ\n- ㅂㅎㅅ', answer: '좋은 사람\n- 박효신' },
  { name: 'ㄱㅅ - ㅂㅈ', answer: '가시 - 버즈' },
  { name: 'ㄴㅇㄱㄹ ㄸㄴㄴ ㅇㅎ-ㅂㅈ', answer: '나에게로 떠나는 여행-버즈' },
  { name: 'ㅅㄹㅅㄹㅇㅇ\n- ㄱㅈㄱ', answer: '사랑사랑이어\n- 김종국' },
  { name: 'ㅌㅇㅇ ㅍㅎㄴ\nㅂㅂ - ㅂ', answer: '태양을 피하는\n방법 - 비' },
  { name: 'ㅈㄴ\n- ㅍㄹㅇㅁㄹ', answer: '자니\n- 프라이머리' },
  { name: 'ㅁㅇㅇ - ㅌㅇ', answer: '만약에 - 태연' },
  { name: 'ㅅㄹ ㅇㅎ\n- ㅂㅈㅇ', answer: '사랑 안해\n- 백지영' },
  { name: 'ㄴㅈㄹ ㅁㄹ\n- ㅂㅈ', answer: '남자를 몰라\n- 버즈' },
  { name: 'ㄱㄹㅇㅅ\n- ㅅㅅㄱ', answer: '거리에서\n- 성시경' },
  { name: 'ㅂㅎㄱ - ㄱㅂㅇ', answer: '비행기 - 거북이' },
  { name: 'ㅈㅅㄹ - ㄷ ㄴㅊ', answer: '잔소리 - 더 넛츠' },
  { name: 'ㅊㅇㅇ ㅅㄹㅇ\nㄷㅇ - ㅂㅎㅅ', answer: '추억은 사랑을\n닮아 - 박효신' },
  { name: 'ㅈㅇ ㄴ\n- ㄷㅇㄴㅁ ㄷㅇ', answer: '죽일 놈\n- 다이나믹 듀오' },
  { name: 'ㄲㅇ - ㅂㅈㅎ', answer: '꿈에 - 박정현' },
  { name: 'ㅎㅈㅇ ㄱㅊㄱ\n- ㅇㅅ', answer: '화장을 고치고\n- 왁스' },
  { name: 'ㄱㅇ ㅂㄱ - ㅌㅇ', answer: '같은 베개 - 테이' },
  { name: 'ㅅㄱㅈ - ㅇㅌㅇ', answer: '세글자 - 엠투엠' },
  { name: 'ㄹㄷㄷ - ㅅㅇㄴ', answer: '링딩동 - 샤이니' },
  { name: 'ㅇㅂㄹㅋㅌㅂㄹ\n- ㅂㅇㄱ', answer: '아브라카타브라\n- 브아걸' },
  { name: 'ㅎㅇㅅ - ㅍㅁㄴ', answer: '핫이슈 - 포미닛' },
  { name: 'ㄴㅂㄷ - ㅇㄷㄱㅅ', answer: '노바디 - 원더걸스' },
  { name: 'ㅅㄹㅇ ㅅ\n- ㅇㅆㄷㅁㅅ', answer: '사랑의 시\n- 엠씨더맥스' },
  { name: 'ㅆㅎ - ㅇㄷㄱㅅ', answer: '쏘핫 - 원더걸스' },
  { name: 'ㅇㅅㄴㅇ - ㅈㅅㅁ', answer: '아시나요 - 조성모' },
  { name: 'ㅇㄹ ㅈㅂ ㅈ\nㅇㅇㄹㅇ - ㅅㅅㄱ', answer: '우린 제법 잘\n어울려요 - 성시경' },
  { name: 'ㄴㅂ ㅇㄷ ㅅㅌㄹ\n- ㅂㅎ', answer: '네버 엔딩 스토리\n- 부활' },
  { name: 'ㅁㅇㅎㅇ - ㄱㄱㅁ', answer: '미안해요 - 김건모' },
  { name: 'ㅈㅈㄹ ㄱㅇ\n- ㄱㅈㄱ', answer: '제자리 걸음\n- 김종국' },
  { name: 'ㅇㅈ - ㅅㅂ', answer: '열정 - 세븐' },
  { name: 'ㅅㄹㅎㄷ ㅎㅈ ㅅ\nㅇㄷㅁ - ㅅㅅㅎ', answer: '사랑해도 헤질 수\n있다면 - 신승훈' },
  { name: 'ㅅㄹㅇㅇ\n- FTㅇㅇㄹㄷ', answer: '사랑앓이\n- FT아일랜드' },
  { name: 'ㅅㄹ ㄱㄱ\nㅁㄷ - ㅇㅍ', answer: '사랑 그게\n뭔데 - 양파' },
  { name: 'ㅈㅁ ㅅㄹㅎㅇㄲ\n- ㅂㄹㅇ ㅇㅇㄷ ㅅㅇ', answer: '정말 사랑했을까\n- 브라운 아이드 소울' },
  { name: 'ㅈㅇㅂ\n- ㅇㅅㅈㅇㄴㅂ', answer: '죄와벌\n- 에스지워너비' },
  { name: 'ㅁㅇ - ㅇㄱㅊ', answer: '미인 - 이기찬' },
  { name: 'ㅇㄱㅁ - ㅇㅇㅂ', answer: '이거면 - 아이비' },
  { name: 'ㅅㄹㅇ ㅎㄱㄹ\nㄴㄱㄱ - ㅌㅇ', answer: '사랑은 향기를\n남기고 - 테이' },
  { name: 'ㄸ ㅎㄴ ㅅㄹ\nㄱㄱ - ㅇㄱㅊ', answer: '또 하나 사랑\n가고 - 이기찬' },
  { name: 'ㅎㄱ ㅎㄷ ㅁ\n- ㅇㅅㄱ', answer: '하기 힘든 말\n- 이승기' },
  { name: 'ㄹㄹㅍ\n- ㅂㅂ, ㅌㅇㄴㅇ', answer: '롤리팝\n- 빅뱅, 투애니원' },
  { name: 'ㅅㄹㅇ ㄱㅅㅇ\nㅅㅋㄷ - ㅂㅈ', answer: '사랑은 가슴이\n시킨다 - 버즈' },
  { name: 'ㅊㄹ - ㅋㄹ', answer: '초련 - 클론' },
  { name: 'ㅁㄱㅇㅅ - ㅂㅎㅅ', answer: '먼곳에서 - 박효신' },
  { name: 'ㄱㅅㄴㅁ - ㅈㅅㅁ', answer: '가시나무 - 조성모' },
  { name: 'ㄱㅎㅇ ㅎ\nㄱㄹㅁ - ㅋ', answer: '결혼을 할\n거라면 - 쿨' },
  { name: 'ㄴㅇ ㅇㅇ\n- ㅇㅊㅈ', answer: '나의 연인\n- 임창정' },
  { name: 'ㅁ - ㄱㅎㅈ', answer: '멍 - 김현정' },
  { name: 'ㅌㅁㄴ - ㅇㅎㄹ', answer: '텐미닛 - 이효리' },
  { name: 'ㅊㅊㅈ - ㄱㄱㅁ', answer: '청첩장 - 김건모' },
  { name: 'ㄷㅅㅇ ㅁㄹㅅㄱㅇ\n- ㅍㅋ', answer: '당신은 모르실거야\n- 핑클' },
  { name: 'ㅎㅎㄹ - ㅇㅅㅇ', answer: '휠릴리 - 이수영' },
  { name: 'ㄱ ㄴㅈ ㄱ ㅇㅈ\n- ㅂㅇㅂ', answer: '그 남자 그 여자\n- 바이브' },
  { name: 'ㅇㄱㄱ - ㅇㅎㄹ', answer: '유고걸 - 이효리' },
  { name: 'ㅎㄷㄹ ㅇㅈ - ㅎㄱㅁ', answer: '흔들린 우정 - 홍경민' },
  { name: 'ㄱ - ㅈㅇㄷ', answer: '길 - 지오디' },
  { name: 'ㅇㅉㄷ - ㅇㄱ', answer: '어쩌다 - 윤건' },
  { name: 'ㅁㅇ ㄴㅇ - ㅂㅇ', answer: '마이 네임 - 보아' },
  { name: 'ㄱㄴㄱ ㅇㅈㅇ - ㄱㅎㅈ', answer: '그녀가 웃잖아 - 김형중' },
  { name: 'ㅈㅅㅅㅇ ㄴㄱㄱㅊㄹ - ㅅㅅㅎ', answer: '전설속의 누군가처럼 - 신승훈' },
  { name: 'ㅁㅇㅎㅇ - ㄱㅁ', answer: '미안해요 - 거미' },
  { name: 'ㅂㄱ ㅅㄷ - ㄱㅂㅅ', answer: '보고 싶다 - 김범수' },
  { name: 'ㅂㅌㄴ - ㅈㅇㄷ', answer: '보통날 - 지오디' },
  { name: 'ㅈㅅ - ㅋ', answer: '진실 - 쿨' },
  { name: 'ㅇㅎㅇ ㅅㄴㅌ\n- ㅇㅇㅂ', answer: '유혹의 소나타\n- 아이비' },
  { name: 'ㅇㅅㄱ - ㄱㅇㅇ', answer: '야상곡 - 김윤아' },
  { name: 'ㅇㅇㄲ\n- ㅇㄷㅎㅂㄷ', answer: '잊을께\n- 윤도현밴드' },
  { name: 'ㅇㅇ - ㅅㅋㅇ', answer: '영원 - 스카이' },
  { name: 'ㅂㄹㅁㅂㄹㅁ\n- ㄱㅈㄱ, ㅇㅅㅈㅇㄴㅂ', answer: '바람만바람만\n- 김종국, 에스지워너비' },
  { name: 'ㄲㅁㅇㄱ - ㅇㄹ', answer: '까만안경 - 이루' },
  { name: 'ㄷㅅ ㅁㄴ ㅅㄱ\n- ㅅㄴㅅㄷ', answer: '다시 만난 세계\n- 소녀시대' },
  { name: 'ㅁㅅㅌ - ㅋㄹ', answer: '미스터 - 카라' },
];

export const music2010Data = [
  { name: 'ㅈㅅㄹ - ㅇㅇㅇ', answer: '잔소리 - 아이유' },
  { name: 'ㅈㅇㄷ ㅁ ㅂㄴ\n- ㅌㅍㅇ', answer: '죽어도 못 보내\n- 투피엠' },
  { name: 'ㄴ ㄸㅁㅇ ㅁㅊ\n- ㅌㅇㄹ', answer: '너 때문에 미쳐\n- 티아라' },
  { name: 'ㅂㅁ ㅈ ㅁㄷㄹ\n- ㅇㅁ', answer: '밥만 잘 먹더라\n- 옴므' },
  { name: 'ㄹㅍ - ㅋㄹ', answer: '루팡 - 카라' },
  { name: 'ㅇㅌㅇㅇ\n- ㅆㅇㅂㄹ', answer: '외톨이야\n- 씨엔블루' },
  { name: 'ㄱㅂ\n- ㄸㄱㅇ ㄱㅈ', answer: '고백\n- 뜨거운 감자' },
  { name: 'ㄴ ㅂㅉㅇ ㄴㄹ\n- ㅂ', answer: '널 붙잡을 노래\n- 비' },
  { name: 'ㄹㄹㅍㄹ\n- ㅌㅇㄹ', answer: '롤리폴리\n- 티아라' },
  { name: 'ㄴㄱ ㅈㅇ ㅈ ㄴㄱ - ㅌㅇㄴㅇ', answer: '내가 제일 잘\n나가 - 투애니원' },
  { name: 'ㅂㄱ ㅇㄴ ㄴㅇ\n- ㅂㅅㅌ', answer: '비가 오는 날엔\n- 비스트' },
  { name: 'ㅈㅇ ㄴ - ㅇㅇㅇ', answer: '좋은 날 - 아이유' },
  { name: 'ㅇㄴㅇㄹㄱ\nㅁㅎㅈㅁ - ㄷㅂㅊ', answer: '안녕이라고\n말하지마 - 다비치' },
  { name: 'ㅂㅂㄷㅂ - ㅅㅋㄹ', answer: '별빛달빛 - 시크릿' },
  { name: 'ㅅㅇㅂㅇ - ㅅㅋㄹ', answer: '샤이보이 - 시크릿' },
  { name: 'ㄱㄴㅅㅌㅇ - ㅆㅇ', answer: '강남스타일 - 싸이' },
  { name: 'ㄴㅎㅈ - ㅆㅅㅌ', answer: '나혼자 - 씨스타' },
  { name: 'ㅎㄹ ㄲ - ㅇㅇㅇ', answer: '하루 끝 - 아이유' },
  { name: 'ㅊㅅㄹ\n- ㅂㅅㅋㅂㅅㅋ', answer: '첫사랑\n- 버스커버스커' },
  { name: 'ㄴㄹ ㅅㄹㅎㄷ\nㅅㄹㅇ - ㅎㄱ', answer: '나를 사랑했던\n사람아 - ㅎㄱ' },
  { name: 'ㅇㄹㅈㅁ ㅈㅂ\n- ㅋㅇㅇ', answer: '이러지마 제발\n- 케이윌' },
  { name: 'ㄴㄹ ㄴ - ㅇㅇㅇ', answer: '너랑 나 - 아이유' },
  { name: 'ㅂㅇㅈㄱ - ㅇㅇㄹ', answer: '보여줄게 - 에일리' },
  { name: 'ㅇㄹㅇ ㅁㅇㅇ\n- ㅍㅁㄴ', answer: '이름이 뭐예요\n- 포미닛' },
  { name: 'ㅂㄲ ㅇㄷ\n- ㅂㅅㅋㅂㅅㅋ', answer: '벚꽃 엔딩\n- 버스커버스커' },
  { name: 'ㅊ ㅅㄹㄴ\n- ㅇㅍㅇㅅ', answer: '첫 사랑니\n- 에프엑스' },
  { name: 'ㅇㅅㅎ - ㅂㅎㅅ', answer: '야생화 - 박효신' },
  { name: 'ㄱㅇㅇㅇ ㅁㄴㅇ\n- ㅇㅇㅇ', answer: '금요일에 만나요\n- 아이유' },
  { name: 'ㄱ ㅈㅇ ㄱㄷㄹ\nㅁㄴ - ㅇㅅㅎ', answer: '그 중에 그대를\n만나 - 이선희' },
  { name: 'ㅎㅇㄹㅂㅇ ㄲ\n- ㅅㅇ, ㄹㅇㄴ', answer: '한여름밤의 꿀\n- 산이, 레이나' },
  { name: 'ㄴㄹㄱ ㄴㅇㅇ\n- ㅇㅇㄹ', answer: '노래가 늘었어\n- 에일리' },
  { name: 'ㄲㅌㄹㄴ\n- ㅇㄹㅈㅋㄹㅁ', answer: '까탈레나\n- 오렌지카라멜' },
  { name: 'ㅇㄹㄱㅁ\nㄱㄹㅈㅁㅈ\n- ㅂㅇㅇ', answer: '이럴거면\n그러지말지\n- 백아연' },
  { name: 'ㄲㄴ ㅁㅇㅇ\n- ㅈㅇㅇㅌ', answer: '꺼내 먹어요\n- 자이언티' },
  { name: 'ㅇㅇㅎ ㅂ\n- ㄹㄲ, ㅇㅈ', answer: '우연히 봄\n- 로꼬, 유주' },
  { name: 'ㄷㄹ ㄴㅈ ㅁㄱ ㄴ\n- ㅁㅆㅇㅇ', answer: '다른 남자 말고 너\n- 미쓰에이' },
  { name: 'ㄷㅅㄹ\n- ㄷㅂㅊ', answer: '두사랑\n- 다비치' },
  { name: 'ㅇㅇㅇㅇ\n- ㅁㅁㅁ', answer: '음오아예\n- 마마무' },
  { name: 'ㅇㄴㅂㅌ ㅇㄹㄴ\n- ㅇㅈㅊㄱ', answer: '오늘부터 우리는\n- 여자친구' },
  { name: 'ㄱㅎㅁㅇㅅ\n- ㄱㅎ', answer: '광화문에서\n- 규현' },
  { name: 'ㅅㄱㅇ ㄷㄹㅅ\n- ㅇㅈㅊㄱ', answer: '시간을 달려서\n- 여자친구' },
  { name: 'ㄴㄱ ㅈㅈㄹ ㅅㄹ\n- ㅇㅊㅈ', answer: '내가 저지른 사랑\n- 임창정' },
  { name: 'ㅂㄴ\n- ㅂㅌㅅㄴㄷ', answer: '봄날\n- 방탄소년단' },
  { name: 'ㄴ ㄴㅁ ㅁㄹㄱ\n- ㅎㅇㅈ', answer: '널 너무 모르고\n- 헤이즈' },
  { name: 'ㄱㄷㄹㄴ ㅅㅊ\n- ㅎㄷㄱ', answer: '그대라는 사치\n- 한동근' },
  { name: 'ㅁㄷ ㄴ ㅁㄷ\nㅅㄱ - ㅍㅋ', answer: '모든 날 모든\n순간 - 폴킴' },
  { name: 'ㅂㅇ ㅂㄴㄴ ㅂ\n- ㅁㅁㅁ', answer: '별이 빛나는 밤\n- 마마무' },
  { name: 'ㅈㅇ ㄱㄷㅇ\nㅇㅎ ㅅ\n- ㅂㅌㅅㄴㄷ', answer: '작은 것들을\n위한 시\n- 방탄소년단' },
  { name: 'ㄴㄹ ㅁㄴ - ㅍㅋ', answer: '너를 만나 - 폴킴' },
  { name: 'ㅈㅈㅎㄴ\nㅇㅇㄷㅇ ㅇㅎ\n- ㅈㄴㅂ', answer: '주저하는\n연인들을 위해\n- 잔나비' },
  { name: 'ㅂㅍㅈ - ㅇㅇㅇ', answer: '밤편지 - 아이유' },
  { name: 'ㅊㄴㅊㄹ ㄴㅇㄱ\nㄱㄱㄷ - ㅇㅇㄹ', answer: '첫눈처럼 너에게\n가겠다 - 에일리' },
  { name: 'ㅂ ㅅㄹ ㅂㄲ ㅁㄱ\n- ㅎㅇㅍ, ㅇㅇㅇ', answer: '봄 사랑 벚꽃 말고\n- 하이포, 아이유' },
  { name: 'ㅇㄷㅇㄷ\n- ㅇㅆㄷㅁㅅ', answer: '어디에도\n- 엠씨더맥스' },
  { name: 'ㅂㄹㄱㅇ\n- ㄴㅇ', answer: '바람기억\n- 나얼' },
  { name: 'ㅅㅁ - ㅁㄹㅁㅅ', answer: '선물 - 멜로망스' },
  { name: 'ㄴㅇ ㅇㅇ - ㅇㅇㅇ', answer: '너의 의미 - 아이유' },
  { name: 'ㅈㄴ - ㅇㅈㅅ', answer: '좋니 - 윤종신' },
  { name: 'ㅂㄷ ㅇㄱ ㄱㄹㅅ\n- ㅎㅇㅈ', answer: '비도 오고 그래서\n- 헤이즈' },
  { name: 'ㅇㅈㄹ ㅈㄱ\n- ㅂㅃㄱㅅㅊㄱ', answer: '우주를 줄게\n- 볼빨간사춘기' },
  { name: 'ㅁㄹ ㅁㄹ\nㅋㄹㅅㅁㅅ\n- ㅇㅇㅇ', answer: '미리 메리\n크리스마스\n- 아이유' },
  { name: 'ㄸ ㄷㅅ ㅅㄹ\n- ㅇㅊㅈ', answer: '또 다시 사랑\n- 임창정' },
  { name: 'ㄴ ㅅㄹㅎㅈ ㅇㅇ\n- ㅇㅂㅈㅋㅍ', answer: '널 사랑하지 않아\n- 어반자카파' },
  { name: 'ㅆ\n- ㅅㅇ, ㅈㄱㄱ', answer: '썸\n- 소유, 정기고' },
  { name: 'ㅅㄹㅇ ㅎㄷ\n- ㅇㅇㅋ', answer: '사랑을 했다\n- 아이콘' },
  { name: 'ㄲㅅㄹ - ㄱㅂㅅ', answer: '끝사랑 - 김범수' },
  { name: 'ㅃㄱ ㅁ\n- ㄹㄷㅂㅂ', answer: '빨간 맛\n- 레드벨벳' },
  { name: 'ㅍㄹㅌ - ㅇㅇㅇ', answer: '팔레트 - 아이유' },
  { name: 'ㅈㄷㄱ ㅁㅎ\n- ㅂㅃㄱㅅㅊㄱ', answer: '좋다고 말해\n- 볼빨간사춘기' },
  { name: 'ㄱㅈㅁㅇㅇ ㄱㄷ\n- ㅇㅈ', answer: '걱정말아요 그대\n- 이적' },
  { name: 'ㅇㅅ ㅂㅂㄷ\n- ㅂㅅㅋ ㅂㅅㅋ', answer: '여수 밤바다\n- 버스커 버스커' },
  { name: 'ㄸㄷㄸㄷ\n- ㅂㄹㅍㅋ', answer: '뚜두뚜두\n- 블랙핑크' },
  { name: 'ㅈㄴㅇㄷ\n- ㄴㄹ', answer: '지나오다\n- 닐로' },
  { name: 'ㄱㄴㅊㄹ\n- ㅈㄷㅊ', answer: '그날처럼\n- 장덕철' },
  { name: 'ㄴㅁ ㅇㄷㄴ ㅇㅇ\n- ㅂㅃㄱㅅㅊㄱ', answer: '나만 안되는 연애\n- 볼빨간사춘기' },
  { name: 'ㅎㅅ - ㅇㅎㅇ', answer: '한숨 - 이하이' },
  { name: 'ㄴㅇㄷㅁ - ㅈㅅㅎ', answer: '너였다면 - 정승환' },
  { name: 'ㅇㅎ - ㅂㅃㄱㅅㅊㄱ', answer: '여행 - 볼빨간사춘기' },
  { name: 'ㄱㄹㅇㅎㄷ\n- ㅂㅌㅂ', answer: '그리워하다\n- 비투비' },
  { name: 'ㅁㅈㅁㅊㄹ - ㅂㄹㅍㅋ', answer: '마지막처럼 - 블랙핑크' },
  { name: 'ㅂㅂㅂ - ㅂㅂ', answer: '뱅뱅뱅 - 빅뱅' },
  { name: 'ㅇㄴㅈㅌ - ㅇㄴㅇ', answer: '에너제틱 - 워너원' },
  { name: 'ㅂㅈㄴ - ㅂㄹㅍㅋ', answer: '불장난 - 블랙핑크' },
  { name: 'ㅇㅎㄷㄱ- ㅈㅇㅇㅌ', answer: '양화대교- 자이언티' },
  { name: 'ㅇㅇㅈ - ㅈㅈㅇ', answer: '안아줘 - 정준일' },
  { name: 'ㅅㄴ - ㅇㅎ', answer: '소녀 - 오혁' },
  { name: 'ㄱㄹㅅㄷ - ㅂㅇㅇ', answer: '가라사대 - 비와이' },
  { name: 'ㅆ ㅌㄲㅇ\n- ㅂㅃㄱㅅㅊㄱ', answer: '썸 탈꺼야\n- 볼빨간사춘기' },
  { name: 'ㅂ - ㅍㅋ', answer: '비 - 폴킴' },
  { name: 'ㅇㄸㅇㄲ - ㅆㅇ', answer: '어땠을까 - 싸이' },
  { name: 'ㄷㅇㅇㅈㅁ - ㅎㅇㅈ', answer: '돌아오지마 - 헤이즈' },
  { name: 'ㅃㅃ - ㅇㅇㅇ', answer: '삐삐 - 아이유' },
  { name: 'ㅅ - ㅂㅎㅅ', answer: '숨 - 박효신' },
  { name: 'ㅇㅇㅇㅇ - ㅎㅇ', answer: '위잉위잉 - 혁오' },
  { name: 'ㅇ ㅅㄹ - ㄷㅂㅊ', answer: '이 사랑 - 다비치' },
  { name: 'ㅅㅁㅅ - ㅇㅇㅇ', answer: '스물셋 - 아이유' },
  { name: 'ㅊㄴㅊㄹ ㄴㅇㄱ\nㄱㄱㄷ - ㅂㅅㅋ ㅂㅅㅋ', answer: '첫눈처럼 너에게\n가겠다 - 버스커 버스커' },
  { name: 'ㄱㄸ ㅎㅇㅈㅁ ㄷ\n- ㄹㅇㅋ', answer: '그때 헤어지면 돼\n- 로이킴' },
  { name: 'ㅍ ㄸ ㄴㅁ\n- ㅂㅌㅅㄴㄷ', answer: '피 땀 눈물\n- 방탄소년단' },
  { name: 'ㅇㄹ ㄴ ㅇㄹ ㅂ\n- ㅇㅁ', answer: '오랜 날 오랜 밤\n- 악뮤' },
];

export const music2020Data = [
  { name: 'ㅇㅁㄴㄹ - ㅈㅋ', answer: '아무노래 - 지코' },
  { name: 'ㅇㄹㅎ - ㅈㅈㅅ', answer: '아로하 - 조정석' },
  { name: 'ㅇㅇ - ㅇㅇㅇ', answer: '에잇 - 아이유' },
  { name: 'ㅅㅈ - ㄱㅎ', answer: '시작 - 가호' },
  { name: 'ㅁㅇㅇ ㄷㄹㅇ\n- ㅇㅇㅇ', answer: '마음을 드려요\n- 아이유' },
  { name: 'ㅊㅇㅊㄹ\n- ㅇㅆㄷㅁㅅ', answer: '처음처럼\n- 엠씨더맥스' },
  { name: 'ㅅㅉ ㅅㄹㅇ\n- ㅇㅁㅇㄱ', answer: '살짝 설렜어\n- 오마이걸' },
  { name: 'ㄷㅅ ㅇㄱ\nㅂㄷㄱ\n- ㅆㅆㄹ', answer: '다시 여기\n바닷가\n- 씨씨를' },
  { name: 'ㅅㄹㅎㄱ\nㄷ ㅈ ㅇㅇㅇ\n- ㅈㅁㄷ', answer: '사랑하게\n될 줄 알았어\n- ㅈㅁㄷ' },
  { name: 'ㄴㄹ ㅅㄹㅎㄱ\nㅇㅇ - ㅂㅎ', answer: '너를 사랑하고\n있어 - 백현' },
  { name: 'ㄴㄴㄴㄴ - ㅈㅅ', answer: '눈누난나 - 제시' },
  { name: 'ㅅㄷ ㄲㅇ\nㅁㅇ ㅈㄷ\n- ㅂㅎㅇ', answer: '시든 꽃에\n물을 주듯\n- 박혜원' },
  { name: 'ㅎㄹㅎㅈ ㅇㅇ\nㄱㅂ - ㄱㅎ', answer: '화려하지 않은\n고백 - 규현' },
  { name: 'ㅍㅈㅁㅊ\n- ㅎㅇㅇ', answer: '포장마차\n- 황인욱' },
  { name: 'ㅅㄹㅇ ㅇㅅㅇ\nㅇㅇㄷㅁ\n- ㅇㅈㅎ', answer: '사랑에 연습이\n있었다면\n- 임재현' },
  { name: 'ㄱㄷ ㄱㅇ\nㄴㅅㄹ\n- ㅇㅂㅈㅋㅍ', answer: '그대 고운\n내사랑\n- 어반자카파' },
  { name: 'ㅅㅊ - ㅇㅇㅈ', answer: '시차 - 우원재' },
  { name: 'ㄷㄷㄷㄷ\n- ㅇㅈㅇㅇㄷ', answer: '덤디덤디\n- 여자아이들' },
  { name: 'ㄱㄷㄹㄴ ㅅ\n- ㅌㅇ', answer: '그대라는 시\n- 태연' },
  { name: 'ㄹㄹ\n- ㅂㄹㅇㅂㄱㅅ', answer: '롤린\n- 브레이브걸스' },
  { name: 'ㄹㅇㄹ - ㅇㅇㅇ', answer: '라일락 - 아이유' },
  { name: 'ㅅㅎㄷ - ㅇㅁㅈ', answer: '신호등 - 이무진' },
  { name: 'ㅂㅎㄴㅇ ㅂㅇ\n- ㄱㅅ', answer: '밤하늘의 별을\n- 경서' },
  { name: 'ㅇㄹㄷ ㄴㄹ\n- ㅅㅌㄷ ㅇㄱ', answer: '오래된 노래\n- 스탠딩 에그' },
  { name: 'ㅊㅁㅂㄹ\n- ㅂㄹㅇㅂㄱㅅ', answer: '치맛바람\n- 브레이브걸스' },
  { name: 'ㅇㅇㅇ ㄴㅇ ㅂㄷ\n- ㅇㅇㅇ', answer: '아이와 나의 바다\n- 아이유' },
  { name: 'ㅁㄹㅇ - ㅎㅅ', answer: '마리아 - 화사' },
  { name: 'ㅈㅈㅁ\n- ㅎㅅ, ㄹㄲ', answer: '주지마\n- 화사, 로꼬' },
  { name: 'ㅈㅇ ㅇㅈ\nㅇㄴㅇ - ㅈㅂㅈ', answer: '잠이 오질\n않네요 - 장범준' },
  { name: 'ㅅㄹㅇㄱ ㅂ\n- ㅁㄹㅁㅅ', answer: '사랑인가 봐\n- 멜로망스' },
  { name: 'ㅅㄹㅇ ㄴ\nㄷㅁㄱ - ㅇㅇㅇ', answer: '사랑은 늘\n도망가 - 임영웅' },
  { name: 'ㅊㅈㄱㅂ - ㄱㅁㅅ', answer: '취중고백 - 김민석' },
  { name: 'ㅂㅇㄹㄱㅇㄱㅇ\n- ㅂㅂ', answer: '봄여름가을겨울\n- 빅뱅' },
  { name: 'ㅈㅇㄹㄱ ㅎㅈ\n- ㅂㄴㅌ', answer: '정이라고 하자\n- 빅나티' },
  { name: 'ㅎㅈㅁㅁ\n- ㅅㅋㄷㅁ', answer: '회전목마\n- 소코도모' },
  { name: 'ㄷㄹㅁ - ㅇㅇㅇ', answer: '드라마 - 아이유' },
  { name: 'ㄴㅇ ㅁㄷ ㅅㄱ\n- ㅅㅅㄱ', answer: '너의 모든 순간\n- 성시경' },
  { name: 'ㅅㅃ - ㅈㅋ', answer: '새삥 - 지코' },
  { name: 'ㄴㅇ ㅇㅈㅇ\n- ㅇㅁㅈ', answer: '눈이 오잖아\n- 이무진' },
  { name: 'ㅅㄱㅇ ㅈㅍㅅ\n- ㅇㅎ', answer: '사건의 지평선\n- 윤하' },
  { name: 'ㄱㅂ\n- ㅅㅅㅊ', answer: '고백\n- 십센치' },
  { name: 'ㄴㅎ - ㅇㅁ', answer: '낙하 - 악뮤' },
  { name: 'ㅇㄴㄷ ㅂㄴㄴ\nㄴㅇㄱ -ㅁㅋㅌ', answer: '오늘도 빛나는\n너에게 -마크툽' },
  { name: 'ㅊㄱㄹ ㅂㄹ\n- ㅅㄷ', answer: '취기를 빌려\n- 산들' },
  { name: 'ㅎㄹㅇㅇ ㄲ\n- ㅇㅁ', answer: '후라이의 꿈\n- 악뮤' },
  { name: 'ㅎㅇㅈㅈ ㅁㅎㅇ\n- ㅂㅈㅈ', answer: '헤어지자 말해요\n- 박재정' },
  { name: 'ㅅㅁㅇㅅ ㄲㅇ\nㅍㅇㄷ - ㅇㄷ', answer: '사막에서 꽃을\n피우듯 - 우디' },
  { name: 'ㅋㅋ\n- ㅇㅈㅇㅇㄷ', answer: '퀸카\n- 여자아이들' },
  { name: 'ㅈ ㅈㄴㅈ ㅇㄹ\n- ㅊㅇㄹ', answer: '잘 지내자 우리\n- 최유리' },
  { name: 'ㅍㅇㅌ ㅎㅇㅈ\n- ㅂㅅㅅ', answer: '파이팅 해야지\n- 부석순' },
  { name: 'ㅂㅇㄱ - ㅂㅂ', answer: '밤양갱 - 비비' },
  { name: 'ㅂㅇ ㄹㅅㄷ\n- ㅇㅈㅎ', answer: '비의 랩소디\n- 임재현' },
  { name: 'ㅇㅍㅅㄷ - ㅇㅁㅈ', answer: '에피소드 - 이무진' },
  { name: 'ㄱㄷㅁ ㅇㄷㅁ\n- ㄴㄷㅋㄴㅅ', answer: '그대만 있다면\n- 너드커넥션' },
  { name: 'ㅇㅅ - ㅂㅈ', answer: '인사 - 범진' },
  { name: 'ㄱ ㅇ ㄱㅌ - ㄹㅇㅈ', answer: '겟 어 기타 - 라이즈' },
  { name: 'ㅎ ㅍㅇㅈㄱ\nㄷ ㅅ ㅇㄱ\n- ㄷㅇㅅㅅ', answer: '한 페이지가\n될 수 있게\n- 데이식스' },
  { name: 'ㅎㅇ ㅂㅇ\n- ㄴㅈㅅ', answer: '하입 보이\n- 뉴진스' },
  { name: 'ㅅㅍ ㅅㅇ\n- ㄴㅈㅅ', answer: '슈퍼 샤이\n- 뉴진스' },
  { name: 'ㄷㅌ - ㄴㅈㅅ', answer: '디토 - 뉴진스' },
  { name: 'ㅅㄹㅎ ㅅㅂㅇ\n- ㅂㅃㄱㅅㅊㄱ', answer: '사랑할 수밖에\n- 볼빨간사춘기' },
  { name: 'ㄱㅁ ㅅㅇㅇ\nㅍㅇㄴ ㅈㅁ\n- ㅎㅇㅋ', answer: '건물 사이에\n피어난 장미\n- 하이키' },
  { name: 'ㄷㄹㅁ - ㅇㅅㅍ', answer: '드라마 - 에스파' },
  { name: 'ㅌㄷ ㅂㅇ\n- ㅅㅌㅇㅆ', answer: '테디 베어\n- 스테이씨' },
  { name: 'ㅅㅇㄱ - ㅅㅂㅌ', answer: '손오공 - 세븐틴' },
  { name: 'ㄲ - ㅈㅅ', answer: '꽃 - 지수' },
  { name: 'ㄱㄹㄷㅇㅅ - ㅅㅅㅊ', answer: '그라데이션 - 십센치' },
  { name: 'ㅁㄹ - ㅎㄱ', answer: '물론 - 허각' },
  { name: 'ㅇㄹㅂ - ㅇㅇㅂ', answer: '일레븐 - 아이브' },
  { name: 'ㅍㅇㄹㅅ\n- ㄹㅅㄹㅍ', answer: '피어리스\n- 르세라핌' },
  { name: 'ㅇㄹㅌㄱㄹ\n- ㅇㅎ', answer: '오르트구름\n- 윤하' },
  { name: 'ㅂㅇ ㄴㄴ\nㄴㅇㄱ - ㄷ', answer: '빛이 나는\n너에게 - 던' },
  { name: 'ㄴㅅㅅ - ㅅㅎㅇ', answer: '니소식 - 송하예' },
  { name: 'ㅈㄲ ㅅㄱ ㄷㄲ\n- ㅇㅁㅈ', answer: '잠깐 시간 될까\n- 이무진' },
  { name: 'ㅁㅇ ㅂ - ㅇㅇㄷ', answer: '마이 백 - 아이들' },
  { name: 'ㄹㅂ ㄷㅇㅂ - ㅇㅇㅂ', answer: '러브 다이브 - 아이브' },
  { name: 'ㅌㅂㅇ - ㅇㅇㄷ', answer: '톰보이 - 아이들' },
  { name: 'ㅍ ㅁㅇ ㄹㄷ\n- ㄹㄷㅂㅂ', answer: '필 마이 리듬\n- 레드벨벳' },
  { name: 'ㅇㅌㅅ - ㄴㅈㅅ', answer: '어텐션 - 뉴진스' },
  { name: 'ㅇㅍㅌ ㄹㅇㅋ\n- ㅇㅇㅂ', answer: '애프터 라이크\n- 아이브' },
  { name: 'ㄴㅅㅌ ㄹㅂ\n- ㅇㅅㅍ', answer: '넥스트 레벨\n- 에스파' },
  { name: 'ㄱㄴㄷㄹ - ㅂㅈㅂ', answer: '가나다라 - 박재범' },
  { name: 'ㅅㅌㄹㅂㄹ ㅁ\n- ㅇㅇㅇ', answer: '스트로베리 문\n- 아이유' },
  { name: 'ㄴㄹ ㅅㄱㅎ\n- ㅈㅅㅋ', answer: '너를 생각해\n- 주시크' },
  { name: 'ㅇㅈㄴ ㅅㄹㅎ\n- ㅋㅇㅅ', answer: '언제나 사랑해\n- 케이시' },
  { name: 'ㅇㄹㄱ ㅎㅇㅈㅇ\nㅎㄷ ㅇㅇ - ㅂㅂ', answer: '우리가 헤어져야\n했던 이유 - 비비' },
  { name: 'ㄷㄲㅂㅂ - ㅇㅅㅍ', answer: '도깨비불 - 에스파' },
  { name: 'ㅅㄹ - ㅅㅅㅊ', answer: '서랍 - 십센치' },
  { name: 'ㄴㄷ - ㅇㅇㄷ', answer: '누드 - 아이들' },
  { name: 'ㄱㅇㅈ - ㅇㅇㅇ', answer: '겨울잠 - 아이유' },
  { name: 'ㅂㅇ ㄷㅅ - ㅇㅁㅈ', answer: '비와 당신 - 이무진' },
];

export const movieData = [
  { name: '/movie/오징어게임.png', answer: '우린 깐부잖아' },
  { name: '/movie/해바라기.png', answer: '꼭 그렇게..\n다 가져가야만..\n속이 후련했냐!' },
  { name: '/movie/곡성.png', answer: '뭣이 중헌디!' },
  { name: '/movie/박하사탕.png', answer: '나 다시 돌아갈래 ~' },
  { name: '/movie/극한직업.png', answer: '지금까지\n이런 맛은 없었다.\n이것은 갈비인가 통닭인가' },
  { name: '/movie/타짜.png', answer: '묻고 더블로 가!' },
  { name: '/movie/지붕뚫고 하이킥.png', answer: '이 빵꾸똥꾸야!' },
  { name: '/movie/아저씨.png', answer: '이거 방탄유리야\n이 개**야!' },
  { name: '/movie/내부자들.png', answer: '모히또 가가지고\n몰디브나 한 잔 할라니까' },
  { name: '/movie/도깨비.png', answer: '날이 좋아서,\n날이 좋지 않아서,\n날이 적당해서\n모든 날이 좋았다' },
  { name: '/movie/타짜2.png', answer: '쏠 수 있어!' },
  { name: '/movie/최고의 사랑.png', answer: '극 뽁 ~' },
  { name: '/movie/어게인 마이 라이프.png', answer: '진행시켜.' },
  { name: '/movie/야인시대.png', answer: '4딸라' },
  { name: '/movie/기생충.png', answer: '너는 다 계획이 있구나' },
  { name: '/movie/친구.png', answer: '느그 아부지 머하시노.' },
  { name: '/movie/사랑했나봐.png', answer: '예나..선정이 딸이에요' },
  { name: '/movie/타짜3.png', answer: '예림이! 그 패 봐봐,\n혹시 장이야?' },
  { name: '/movie/상속자들.png', answer: '나, 너 좋아하냐?' },
  { name: '/movie/부당거래.png', answer: '호의가 계속되면,\n그게 권리인 줄 알아요' },
  { name: '/movie/아이리스.png', answer: '아악 안돼' },
  { name: '/movie/천국의 계단.png', answer: '사랑은, 돌아오는 거야 ~' },
  { name: '/movie/파리의 연인.png', answer: '이 안에 너 있다' },
  { name: '/movie/내 머리속의 지우개.png', answer: '이거 마시면\n나랑 사귀는 거다' },
  { name: '/movie/올드보이.png', answer: '누구냐, 넌' },
  { name: '/movie/친절한 금자씨.png', answer: '너나 잘하세요' },
  { name: '/movie/스카이캐슬.png', answer: '전적으로 저를\n믿으셔야 합니다' },
  { name: '/movie/더글로리.png', answer: '멋지다 연진아 ~' },
  { name: '/movie/살인의추억.png', answer: '밥은 먹고 다니냐?' },
  { name: '/movie/범죄도시.png', answer: '어, 아직 싱글이야' },
  { name: '/movie/태조 왕건.png', answer: '누구인가?\n누가 기침소리를\n내었는가?' },
  { name: '/movie/어벤져스(인피니티 워).png', answer: '와칸다 포에버' },
  { name: '/movie/어벤져스(엔드게임).png', answer: 'I am Iron Man' },
  { name: '/movie/변호인.png', answer: '국가란 국민입니다!' },
  { name: '/movie/겨울왕국1.png', answer: 'Do you wanna build a snowman?' },
  { name: '/movie/킹스맨.png', answer: 'Manners, Maketh, Man' },
  { name: '/movie/무한도전.png', answer: '어데가서 무기받노 ~' },
  { name: '/movie/바람.png', answer: '내 나이?\n서른마흔다섯살이다.' },
  { name: '/movie/범죄도시2.png', answer: '너 납치된거야' },
  { name: '/movie/재벌집 막내아들.png', answer: '몇개고? 밥알 말이다' },
  { name: '/movie/상속자들2.png', answer: '사탄들의 학교에\n루시퍼의 등장이라..' },
  { name: '/movie/미래를 보는 소년.png', answer: '이따 5시에 호떡집에서\n불이 날거에요' },
  { name: '/movie/쌈마이웨이.png', answer: '예쁜 척 하는게 아니라\n예쁘게 태어난곤데 ~' },
  { name: '/movie/러브레터.png', answer: '오겡끼데스까 ~' },
  { name: '/movie/암살.png', answer: '구멍이 두개지요' },
  { name: '/movie/명량.png', answer: '신에게는 아직\n12척의 배가 남아있사옵니다' },
  { name: '/movie/관상.png', answer: '내가 왕이 될 상인가' },
  { name: '/movie/7번방의 선물.png', answer: '예승이 콩먹어 콩 비타민' },
  { name: '/movie/가을동화.jpeg', answer: '웃기지마\n돈으로 사겠어\n얼마면 돼' },
  { name: '/movie/펜트하우스.png', answer: '벌써 떨리는 군' },
  { name: '/movie/꽃보다남자.jpeg', answer: '시켜줘 그럼\n금잔디 명예소방관' },
  { name: '/movie/꽃보다남자2.jpeg', answer: '하얀 천과\n바람만 있으면\n어 디든 갈 수 있어' },
  { name: '/movie/다모.jpeg', answer: '아프냐 나도 아프다' },
  { name: '/movie/로망스.jpeg', answer: '난 선생이고\n넌 학생이야' },
  { name: '/movie/말아톤.jpeg', answer: '초원이 다리는\n백만불짜리 다리' },
  { name: '/movie/명성황후.jpeg', answer: '내가 조선의 국모다' },
  { name: '/movie/미스터션샤인.jpeg', answer: '러브가 무엇이오' },
  { name: '/movie/범죄도시.jpeg', answer: '진실의 방으로' },
  { name: '/movie/부부의세계.jpeg', answer: '사랑에 빠진게\n죄는 아니잖아' },
  { name: '/movie/사랑과전쟁.jpeg', answer: '괜찮아요?\n많이 놀랐죠?' },
  { name: '/movie/서울의봄.jpeg', answer: '실패하면 반역\n성공하면 혁명 아닙니까' },
  { name: '/movie/신데렐라 언니.jpeg', answer: '연습은 하니\n죽도록하는거야' },
  { name: '/movie/응팔.jpeg', answer: '아이고 김사장\n이거 정말\n반갑구만 반가워요' },
  { name: '/movie/이누야샤.jpeg', answer: '안녕히계세요 여러분~' },
  { name: '/movie/재벌집 막내아들.jpeg', answer: '도준이 내 손주다' },
  { name: '/movie/지붕뚫고하이킥.jpeg', answer: '띠드버거사주세요' },
  { name: '/movie/지붕뚫고하이킥2.jpeg', answer: '세경씨\n그렇게 안 봤는데\n정말 무서운 사람이네' },
  { name: '/movie/친구.jpeg', answer: '고마해라\n마이 무따 아이가' },
  { name: '/movie/친구2.jpeg', answer: '내가 니 시다바리가' },
  { name: '/movie/친구3.jpeg', answer: '니가 가라 하와이' },
  { name: '/movie/코난.jpeg', answer: '내 이름은 코난\n탐정이죠' },
  { name: '/movie/타짜.jpeg', answer: '나 이대 나온 여자야' },
  { name: '/movie/파리의 연인2.png', answer: '저 사람이 내 사람이다\n저 남자가 내 남자다\n왜 말을 못하냐고' },
];
